# Zombes4Bukkit v1.0 by md_5
debug: true
# Death
death:
  enabled: true
  dropInv: false
  loseExp: false
  healthPenalty: 0
# Growth - Does not support Spout
growth:
  enabled: true
  flower: 15
  shroom: 50
  pumpkin: 30
  sapling: 20
  reed: 10
  rooting: true
  planting: true
  rootingSpace: 3
  rootingTime: 10
# NoClip
noclip:
  enabled: true
  messages: true

