# Zombes4Bukkit v1.0 by md_5
debug: true
# Death
death:
  enabled: true
  dropInv: false
  loseExp: false
  healthPenalty: 0
# Growth - Spreading does not support Spout
growth:
  enabled: true
  flower: 15
  shroom: 50
  pumpkin: 30
  sapling: 20
  reed: 10
  rooting: true
  planting: true
  rootingSpace: 3
  rootingTime: 10
# NoClip
noclip:
  enabled: true
  messages: true
# Boom - Not implemented yet
boom:
  enabled: true
  boomDropChance: 30
  boomDropOreChance: 100
  boomScaleTNT: 1.0
  boomScaleCreeper: 1.0
  boomScaleFireball: 0.99
  boomSafeRange: 16
# Spawn - Not implemented yet
spawn:
  enabled: true
  allowInNonAir: false
  allowOnNonNatural: false
  allowOnGrass: true
  allowOnCobble: true
  allowOnSand: true
  allowOnGravel: true
  allowOnTree: false
  allowOnSandstone: false
  #
  pigReduction: 75
  chickenReduction: 25
  cowReduction : 0
  sheepReduction: 0
  squidReduction: 0
  wolfReduction : 0
  spiderReduction: 0
  skeletonReduction: 0
  creeperReduction: 0
  zombieReduction: 0
  slimeReduction: 0
  ghastReduction: 0
  pigZombieReduction: 0
  caveSpiderReduction: 0
  endermanReduction: 0
  silverfishReduction: 0
