# NoClip v1.2 by md_5
# magicToken: ยง6Zombe's NoClip is allowed on this server &f &f &4 &0 &9 &6
messages: true
# enableMessage: &aNoClip successfully enabled
# disableMessage: &aNoClip successfully disabled