name: Zombes4Bukkit
version: 0.1
description: The one and only official Bukkit plugin to allow the use of Zombe's NoClip mod. Also contains many features from Zombe's single player mod collection
author: md_5

main: com.md_5.zmod.Plugin

commands:
  noclip:
    description: Internal Zombe's NoClip enable / disable command
    permission: noclip

permissions:
  zombes.noclip:
    description: Allow the use of Zombe's NoClip mod
    default: op
  noclip:
    description: Legacy permission to allow the use of Zombe's NoClip mod
    default: op
