name: Zombes4Bukkit
version: 1.2
description: The one and only official Bukkit plugin to allow the use of Zombe's NoClip mod
author: md_5

main: com.md_5.zmod.Plugin
softdepend: [Spout]

commands:
  noclip:
    description: Internal Zombe's NoClip enable / disable command
    permission: noclip

permissions:
  noclip:
    description: Allow the use of Zombe's NoClip mod
    default: op
